### ISSUE TITLE
'NoneType' object has no attribute 'browse'

### ISSUE THREAD

**Issue by Yenthe666** [YannickB/saas#2]
Hi Yannick

Go to SaaS > Configurations > Logs and create a new records which you leave fully blank. Only change the state to 'OK'. and save the record. Example:
<img src="http://i.imgur.com/PUnxh59.png" alt="Example record to crash module" />
You will get the following error after saving it:
<img src="http://i.imgur.com/tAnkY8i.png" alt="Error" />

To fix this you can create a try catch in the _get_name function (file execute.py in module saas). I haven't digged through your whole code but I assume something is missing that it should have that you will now find. :)
Your original code:

```
    def _get_name(self, cr, uid, ids, field_name, arg, context=None):
        res = {}
        for log in self.browse(cr, uid, ids, context=context):
            model_obj = self.pool.get(log.model)
            record = model_obj.browse(cr, uid, log.res_id, context=context)
            res[log.id] = ''
            if record and hasattr(record, 'name'):
                res[log.id] = record.name
        return res
```

Possible fix:

```
    def _get_name(self, cr, uid, ids, field_name, arg, context=None):
        res = {}
        for log in self.browse(cr, uid, ids, context=context):
            model_obj = self.pool.get(log.model)
            try:
                record = model_obj.browse(cr, uid, log.res_id, context=context)
                res[log.id] = ''
                if record and hasattr(record, 'name'):
                    res[log.id] = record.name
            except Exception:
                print "murp"
        return res
```

**Comment by YannickB** [comment]
Well I shall find a way to block the manual log creation, the logs are automatically created when we make a manipulation on the orchestrator.

We'll see this when I finish the refactoring, for now let's close the issue

**Comment by Yenthe666** [comment]
Okay! Keep me updated please :)
